//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public int MusteriID { get; set; }
        public int UrunID { get; set; }
        public int Adet { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
